version: "2"

services:
    redis:
        image: redis

    base:
        build: .
        volumes:
            - .:/code

        environment:
            - REDIS_HOST=redis
            - TOKEN=118092144:AAHyj4D1R5XvsbT1cYA3MYYebtUjoei-nGM

        ports:
            - "8000:8000"

    poll:
        extends: base
        links:
            - "redis:redis"

        command: -m ofensivaria.poll

    app:
        extends: base
        links:
            - "redis:redis"
